/*
 * JNCIS-SP (JN0-364) — Service Provider Routing and Switching, Specialist
 * Question data organized into multiple independent mock exams.
 *
 * Original, exam-style items written to the publicly published JNCIS-SP
 * objectives for study purposes. Not copied from any proprietary exam.
 *
 * Domain keys:
 *   PIR, OSPF, ISIS, BGP, L2, STP, MPLS, VPN, IPV6, TUNNELS, HA, COS
 */
const SP_CERT = {
  id: "SP",
  code: "JN0-364",
  name: "JNCIS-SP",
  fullName: "Service Provider Routing and Switching, Specialist",
  track: "Service Provider Routing & Switching",
  junos: "Junos OS 25.2",
  realExam: "65 questions / 90 minutes",
  domains: {
    PIR:     "Protocol-Independent Routing",
    OSPF:    "Open Shortest Path First (OSPF)",
    ISIS:    "IS-IS",
    BGP:     "Border Gateway Protocol (BGP)",
    L2:      "Layer 2 Bridging, VLANs & Switching",
    STP:     "Spanning Tree Protocols",
    MPLS:    "MPLS Fundamentals (LDP / RSVP-TE)",
    VPN:     "MPLS VPNs (L3VPN / L2VPN / VPLS)",
    IPV6:    "IPv6",
    TUNNELS: "Tunnels (GRE / IP-IP)",
    HA:      "High Availability",
    COS:     "Class of Service"
  },
  exams: [
    // ============================================================
    {
      id: "SP-A",
      name: "Mock Exam A — Full Blueprint",
      description: "A balanced 25-question exam across all SP domains, with strong MPLS/VPN coverage.",
      questions: [
        { id: "A1", domain: "MPLS",
          text: "In MPLS, what does the penultimate (second-to-last) LSR do when penultimate-hop popping (PHP) is in effect?",
          options: ["Swaps the label and forwards","Pops the outer label so the egress router receives an unlabeled (or exposed-inner-label) packet","Pushes an additional label","Drops the packet"],
          answer: 1, multi: false,
          explanation: "With PHP the penultimate LSR pops the outer transport label so the egress PE does a single IP (or inner-label) lookup instead of two lookups. In Junos this is signaled with an implicit-null (label 3) advertisement." },
        { id: "A2", domain: "MPLS",
          text: "Which label-distribution protocol establishes LSPs by following the IGP shortest path and does NOT support traffic engineering by itself?",
          options: ["RSVP-TE","LDP","BGP-LU","IS-IS"],
          answer: 1, multi: false,
          explanation: "LDP builds LSPs that follow the IGP's shortest path (hop-by-hop) and has no native TE/bandwidth reservation. RSVP-TE supports explicit paths and bandwidth reservation." },
        { id: "A3", domain: "MPLS",
          text: "Which protocol is used in Junos to signal traffic-engineered LSPs with bandwidth reservation and explicit paths?",
          options: ["LDP","RSVP (RSVP-TE)","OSPF","ARP"],
          answer: 1, multi: false,
          explanation: "RSVP-TE signals TE LSPs, supporting explicit-route objects (ERO), bandwidth reservation, and features like fast reroute." },
        { id: "A4", domain: "VPN",
          text: "In an RFC 4364 (2547bis) L3VPN, which construct makes overlapping customer prefixes unique across VRFs when carried in MP-BGP?",
          options: ["Route target","Route distinguisher (RD)","Label stack","Community"],
          answer: 1, multi: false,
          explanation: "The route distinguisher is prepended to the IPv4 prefix to form a unique VPN-IPv4 (VPNv4) route, so overlapping customer prefixes remain distinct. Route targets control import/export among VRFs." },
        { id: "A5", domain: "VPN",
          text: "In an L3VPN, which attribute controls which routes are imported into and exported from a particular VRF?",
          options: ["Route distinguisher","Route target (extended community)","MED","Origin"],
          answer: 1, multi: false,
          explanation: "Route targets (BGP extended communities) determine VRF import/export membership, defining the VPN topology. The RD only provides uniqueness." },
        { id: "A6", domain: "VPN",
          text: "Which MPLS VPN service emulates a multipoint Ethernet LAN across the provider core?",
          options: ["L3VPN (2547bis)","VPLS","L2 circuit (Martini)","6PE"],
          answer: 1, multi: false,
          explanation: "VPLS provides a multipoint-to-multipoint Ethernet LAN emulation across the MPLS core. An L2 circuit is point-to-point; L3VPN is a routed service." },
        { id: "A7", domain: "VPN",
          text: "A point-to-point Layer 2 connection carried over MPLS between two PE interfaces (pseudowire) is commonly called what in Junos?",
          options: ["VPLS instance","L2 circuit / L2VPN pseudowire","L3VPN","GRE tunnel"],
          answer: 1, multi: false,
          explanation: "A point-to-point pseudowire is an L2 circuit (LDP-signaled, 'Martini') or a BGP-signaled L2VPN ('Kompella'), transporting one customer L2 connection across the core." },
        { id: "A8", domain: "BGP",
          text: "Which BGP address family carries L3VPN (VPNv4) routes between PE routers?",
          options: ["inet unicast","inet-vpn (VPNv4) unicast","inet6 unicast","l2vpn signaling for VPLS"],
          answer: 1, multi: false,
          explanation: "MP-BGP with the inet-vpn (VPNv4) family carries RD-qualified customer routes with VPN labels between PEs. The l2vpn family is for BGP-signaled L2VPN/VPLS." },
        { id: "A9", domain: "IPV6",
          text: "Which IPv6 address type begins with FE80::/10 and is valid only on a single link?",
          options: ["Global unicast","Unique local","Link-local","Multicast"],
          answer: 2, multi: false,
          explanation: "Link-local addresses (FE80::/10) are auto-configured per interface and used for on-link operations such as neighbor discovery and next-hop resolution; they are not routed off-link." },
        { id: "A10", domain: "IPV6",
          text: "Which protocol replaces IPv4 ARP for resolving link-layer addresses in IPv6?",
          options: ["ICMPv6 Neighbor Discovery (NDP)","DHCPv6","OSPFv3","SLAAC only"],
          answer: 0, multi: false,
          explanation: "IPv6 uses ICMPv6-based Neighbor Discovery (Neighbor Solicitation/Advertisement) instead of ARP for address resolution, plus Router Solicitation/Advertisement for router discovery." },
        { id: "A11", domain: "OSPF",
          text: "Which OSPF version is used to route IPv6, and how does it identify neighbors?",
          options: ["OSPFv2, by IPv6 address","OSPFv3, by 32-bit Router ID","OSPFv3, by MAC address","OSPFv2, by Router ID"],
          answer: 1, multi: false,
          explanation: "OSPFv3 routes IPv6 (and can support IPv4 via address families). It still uses a 32-bit Router ID to identify routers and runs per-link, using link-local addresses for adjacencies." },
        { id: "A12", domain: "ISIS",
          text: "How does IS-IS support routing both IPv4 and IPv6 within the same protocol instance?",
          options: ["It runs two separate processes","It carries reachability in protocol-specific TLVs (e.g., IPv6 reachability TLV)","It tunnels IPv6 in IPv4","It cannot route IPv6"],
          answer: 1, multi: false,
          explanation: "Because IS-IS runs over Layer 2 and uses TLVs, it carries IPv4 and IPv6 reachability in separate TLVs within one instance (multi-topology or single-topology)." },
        { id: "A13", domain: "TUNNELS",
          text: "You must connect two IPv6 sites across an IPv4-only core without MPLS. Which tunneling option is most appropriate?",
          options: ["An L3VPN","A GRE tunnel carrying IPv6 over IPv4","MACsec","VRRP"],
          answer: 1, multi: false,
          explanation: "A GRE tunnel can encapsulate IPv6 across an IPv4-only transport, providing connectivity between IPv6 islands without native IPv6 or MPLS in the core." },
        { id: "A14", domain: "TUNNELS",
          text: "For IP-IP or GRE tunnels across your network, which technique helps endpoints discover the largest packet size that avoids fragmentation?",
          options: ["Path MTU Discovery (PMTUD)","BFD","LDP","VRRP"],
          answer: 0, multi: false,
          explanation: "Path MTU Discovery lets endpoints learn the smallest MTU along the path (via ICMP 'fragmentation needed'/'packet too big'), so they can size packets to avoid fragmentation across tunnels." },
        { id: "A15", domain: "PIR",
          text: "Which Junos routing table stores the labeled next hops (MPLS/tunnel routes) used to resolve BGP next hops over LSPs?",
          options: ["inet.0","inet.3","mpls.0","inet6.0"],
          answer: 1, multi: false,
          explanation: "inet.3 stores MPLS/tunnel next hops (LSP egress routes) used for BGP next-hop resolution. mpls.0 holds the label-switching (transit) routes; inet.0 is plain IPv4 unicast." },
        { id: "A16", domain: "MPLS",
          text: "Which Junos routing table holds the label-switched (transit) forwarding entries used to swap/pop labels?",
          options: ["inet.0","inet.3","mpls.0","bgp.l3vpn.0"],
          answer: 2, multi: false,
          explanation: "mpls.0 contains label operations (swap/pop) for transit LSRs. inet.3 holds LSP egress next hops for ingress resolution; bgp.l3vpn.0 holds received VPNv4 routes." },
        { id: "A17", domain: "BGP",
          text: "Place the BGP path-selection steps in Junos order (highest priority first).",
          options: ["AS-path → Local preference → Origin → MED","Local preference → AS-path length → Origin → MED","Origin → MED → Local preference → AS-path","MED → AS-path → Local preference → Origin"],
          answer: 1, multi: false,
          explanation: "Junos compares highest Local Preference, then shortest AS-path, then lowest Origin (IGP<EGP<Incomplete), then lowest MED, before EBGP-over-IBGP and IGP metric tie-breakers." },
        { id: "A18", domain: "L2",
          text: "On an MX router, a bridge domain is roughly analogous to what on an EX switch?",
          options: ["A firewall filter","A VLAN","A routing instance of type virtual-router","An aggregated Ethernet bundle"],
          answer: 1, multi: false,
          explanation: "A bridge domain on MX groups logical interfaces into a single Layer 2 broadcast domain, analogous to a VLAN on EX switches, and can be given an IRB for routing." },
        { id: "A19", domain: "OSPF",
          text: "In OSPF, an ABR connects which of the following?",
          options: ["Two autonomous systems","One or more areas to the backbone area","Two different IGPs","Two VRFs"],
          answer: 1, multi: false,
          explanation: "An Area Border Router (ABR) has interfaces in multiple areas, connecting non-backbone areas to area 0 and generating inter-area (Type 3) summaries." },
        { id: "A20", domain: "ISIS",
          text: "Which IS-IS PDU is used to acknowledge and ensure LSP database synchronization on point-to-point links?",
          options: ["Hello (IIH)","Complete Sequence Number PDU (CSNP) / Partial (PSNP)","Router LSA","BPDU"],
          answer: 1, multi: false,
          explanation: "CSNPs summarize the LSP database and PSNPs request/acknowledge specific LSPs, driving database synchronization. IIH PDUs form adjacencies." },
        { id: "A21", domain: "HA",
          text: "Which feature preserves routing-protocol state across an RE switchover on a dual-RE router without relying on neighbors?",
          options: ["Graceful restart","Nonstop Active Routing (NSR)","VRRP","LDP"],
          answer: 1, multi: false,
          explanation: "NSR replicates protocol state to the backup RE (on top of GRES), so adjacencies survive a switchover with no neighbor cooperation. Graceful restart instead relies on helper neighbors." },
        { id: "A22", domain: "COS",
          text: "In an MPLS network, which header field is used by CoS to classify labeled packets on transit LSRs?",
          options: ["DSCP","The EXP / Traffic Class bits in the MPLS label","802.1p in the Ethernet header","TTL"],
          answer: 1, multi: false,
          explanation: "The 3-bit EXP (now 'Traffic Class') field in the MPLS shim header conveys CoS on labeled packets, since transit LSRs do not inspect the inner IP DSCP." },
        { id: "A23", domain: "VPN",
          text: "In a 2547bis L3VPN, how many labels are typically in the stack on a packet crossing the core toward a remote CE?",
          options: ["One label only","Two labels: an outer transport (LSP) label and an inner VPN label","Three labels always","Zero — VPN routes are not labeled"],
          answer: 1, multi: false,
          explanation: "L3VPN uses a two-label stack: the outer transport label routes the packet to the egress PE across the core, and the inner VPN label identifies the target VRF/next hop at the PE." },
        { id: "A24", domain: "IPV6",
          text: "Which notation correctly compresses the address 2001:0db8:0000:0000:0000:0000:0000:0001?",
          options: ["2001:db8::1","2001:db8:0:1","2001::db8::1","2001:0db8:1"],
          answer: 0, multi: false,
          explanation: "Leading zeros in each hextet are dropped and one run of all-zero groups is replaced by '::', giving 2001:db8::1. '::' may appear only once." },
        { id: "A25", domain: "STP",
          text: "Which spanning-tree protocol reduces the number of instances by mapping many VLANs onto a few instances for scalability?",
          options: ["STP","RSTP","MSTP","VSTP"],
          answer: 2, multi: false,
          explanation: "MSTP maps groups of VLANs to a small number of spanning-tree instances (MSTIs), scaling far better than per-VLAN VSTP in large L2 domains." }
      ]
    },
    // ============================================================
    {
      id: "SP-B",
      name: "Mock Exam B — MPLS & VPN Focus",
      description: "A 20-question set weighted toward MPLS, LSPs, and MPLS VPN services.",
      questions: [
        { id: "B1", domain: "MPLS",
          text: "What is the value and meaning of the MPLS 'implicit null' label?",
          options: ["Label 0 — explicit null, keep the label","Label 3 — signals penultimate-hop popping","Label 1 — router alert","Label 16 — first usable label"],
          answer: 1, multi: false,
          explanation: "Label 3 is the implicit-null label; advertising it tells the upstream (penultimate) LSR to pop the label (PHP). Label 0 is explicit null (pop but keep an entry for CoS)." },
        { id: "B2", domain: "MPLS",
          text: "In the MPLS label stack, which bit indicates the bottom of stack?",
          options: ["The TTL field","The S (bottom-of-stack) bit","The EXP bits","The label value itself"],
          answer: 1, multi: false,
          explanation: "The S bit set to 1 marks the bottom label in the stack; the receiving LSR knows the next header is the payload (e.g., IP) rather than another label." },
        { id: "B3", domain: "MPLS",
          text: "Which RSVP-TE object specifies the explicit sequence of hops an LSP must traverse?",
          options: ["Record Route Object (RRO)","Explicit Route Object (ERO)","Label Object","Session Attribute Object"],
          answer: 1, multi: false,
          explanation: "The ERO defines the explicit (strict/loose) path the LSP should take. The RRO records the actual path taken for loop detection and troubleshooting." },
        { id: "B4", domain: "MPLS",
          text: "RSVP-TE fast reroute (link/node protection) provides what benefit?",
          options: ["Compresses the label stack","Pre-establishes a bypass/detour LSP so traffic is locally repaired around a failure in tens of milliseconds","Encrypts LSP traffic","Removes the need for an IGP"],
          answer: 1, multi: false,
          explanation: "FRR pre-signals a bypass (link/node protection) or detour LSP so the point of local repair reroutes traffic almost immediately upon failure, before the head-end resignals." },
        { id: "B5", domain: "MPLS",
          text: "Why does an ingress LSR in Junos need a route in inet.3 to the LSP egress?",
          options: ["To perform ARP","To resolve the BGP next hop over the LSP so labeled forwarding is used","To run OSPF","To build the bridge table"],
          answer: 1, multi: false,
          explanation: "BGP next hops are resolved against inet.3; if the egress PE's loopback is in inet.3 via an LSP, the ingress PE forwards the traffic label-switched over that LSP." },
        { id: "B6", domain: "VPN",
          text: "In a hub-and-spoke L3VPN, how are route targets typically arranged?",
          options: ["All sites share one RT for full mesh","Spokes export a 'spoke' RT and import a 'hub' RT; the hub imports spoke RT and exports hub RT","RTs are not used in hub-and-spoke","Only RDs are used"],
          answer: 1, multi: false,
          explanation: "Asymmetric route-target import/export builds hub-and-spoke: spokes send routes to the hub and receive only hub-originated routes, forcing spoke-to-spoke traffic through the hub." },
        { id: "B7", domain: "VPN",
          text: "Which L2VPN signaling approach uses BGP for auto-discovery and signaling (as opposed to LDP-signaled L2 circuits)?",
          options: ["Martini (RFC 4906/draft-martini)","Kompella (BGP-signaled) L2VPN","6PE","Inter-AS Option A"],
          answer: 1, multi: false,
          explanation: "Kompella L2VPNs use BGP for both auto-discovery and signaling, while Martini-style L2 circuits use targeted LDP and require manual remote-PE/VC-ID configuration." },
        { id: "B8", domain: "VPN",
          text: "In VPLS, how does the PE learn which remote PE to forward a customer Ethernet frame to?",
          options: ["Static ARP only","MAC learning over the pseudowires (mesh) plus flooding of unknown/broadcast frames","OSPF","RSVP"],
          answer: 1, multi: false,
          explanation: "VPLS PEs perform MAC learning across the pseudowire mesh and flood BUM traffic, behaving like a distributed Ethernet switch across the MPLS core." },
        { id: "B9", domain: "VPN",
          text: "Which routing-instance type is used on a PE for an RFC 4364 L3VPN in Junos?",
          options: ["virtual-router","vrf","vpls","l2backhaul-vpn"],
          answer: 1, multi: false,
          explanation: "The 'vrf' instance-type provides per-customer routing tables with route-distinguisher and vrf-import/export (route targets). 'vpls' is for VPLS; 'virtual-router' has no RD/RT VPN semantics." },
        { id: "B10", domain: "VPN",
          text: "A PE-CE routing session most commonly uses which protocol(s) to exchange customer routes?",
          options: ["Only static routes","BGP, OSPF, IS-IS, RIP, or static — configured within the VRF","LDP","RSVP-TE"],
          answer: 1, multi: false,
          explanation: "PE-CE routing can use static, BGP, OSPF, IS-IS or RIP inside the VRF; those routes are redistributed into MP-BGP (VPNv4) for transport across the core." },
        { id: "B11", domain: "MPLS",
          text: "Which statement about LDP is correct?",
          options: ["It requires an explicit path to be configured","It typically relies on the IGP for path selection and uses the IGP next hop","It reserves bandwidth per LSP","It replaces the IGP"],
          answer: 1, multi: false,
          explanation: "LDP is not a routing protocol; it distributes labels for IGP-learned FECs and follows the IGP's shortest path. It performs no bandwidth reservation or explicit routing." },
        { id: "B12", domain: "BGP",
          text: "Why must PE routers usually run MP-BGP as IBGP in a full mesh or via route reflectors?",
          options: ["To exchange LDP labels","To carry VPNv4/inet-vpn routes between all PEs within the AS","To run VRRP","To form OSPF adjacencies"],
          answer: 1, multi: false,
          explanation: "VPNv4 routes are exchanged via IBGP among PEs; because IBGP does not re-advertise between IBGP peers, a full mesh or route reflectors are required for scalability." },
        { id: "B13", domain: "MPLS",
          text: "In Junos, applying 'family mpls' to an interface accomplishes what?",
          options: ["Enables IPv6 on the interface","Allows the interface to send/receive labeled (MPLS) packets","Turns on VRRP","Creates a bridge domain"],
          answer: 1, multi: false,
          explanation: "'family mpls' on the logical interface enables MPLS label processing so the interface can participate in label-switched forwarding; it is required on core-facing interfaces." },
        { id: "B14", domain: "MPLS",
          text: "What does the MPLS TTL do by default when a labeled packet transits the core?",
          options: ["It is ignored","It is decremented at each LSR, providing loop protection like IP TTL","It is copied to the DSCP","It is always set to 255"],
          answer: 1, multi: false,
          explanation: "The MPLS TTL is decremented per hop for loop protection. TTL handling between IP and label (propagate vs. no-propagate) affects whether traceroute reveals core hops." },
        { id: "B15", domain: "VPN",
          text: "Which inter-AS L3VPN option exchanges VPNv4 routes between ASBRs over MP-EBGP and keeps a single labeled hop between them (no per-VRF interfaces)?",
          options: ["Option A (VRF-to-VRF)","Option B (VPNv4 exchange between ASBRs)","Option C (multihop MP-EBGP between RRs with labeled IPv4)","No inter-AS option exists"],
          answer: 1, multi: false,
          explanation: "Option B has ASBRs exchange labeled VPNv4 routes directly over MP-EBGP. Option A uses per-VRF sub-interfaces; Option C uses multihop MP-EBGP between route reflectors with labeled IPv4 for PE loopbacks." },
        { id: "B16", domain: "PIR",
          text: "When both an LDP LSP and an RSVP LSP exist to the same egress, which does Junos prefer for inet.3 by default?",
          options: ["LDP, always","RSVP, because it has a lower default route preference than LDP","Whichever has more hops","Neither — they cannot coexist"],
          answer: 1, multi: false,
          explanation: "By default RSVP has a lower (better) route preference (7) than LDP (9), so the RSVP LSP is preferred in inet.3 for next-hop resolution when both exist." },
        { id: "B17", domain: "MPLS",
          text: "Which Junos command shows the labels being swapped/popped for transit LSPs?",
          options: ["show route table mpls.0","show ospf database","show bridge mac-table","show vrrp"],
          answer: 0, multi: false,
          explanation: "'show route table mpls.0' displays the label-switching entries (incoming label, operation, next hop) for transit MPLS forwarding." },
        { id: "B18", domain: "VPN",
          text: "What problem does the route distinguisher solve that route targets do not?",
          options: ["Deciding VRF import/export","Making otherwise-identical customer prefixes unique in MP-BGP","Encrypting the payload","Reserving bandwidth"],
          answer: 1, multi: false,
          explanation: "The RD guarantees uniqueness of overlapping customer prefixes in the VPNv4 table; route targets separately control which VRFs import/export a route." },
        { id: "B19", domain: "MPLS",
          text: "A Forwarding Equivalence Class (FEC) in MPLS represents what?",
          options: ["A single physical port","A group of packets forwarded the same way over the same LSP","An IGP area","A VLAN"],
          answer: 1, multi: false,
          explanation: "A FEC is a set of packets treated identically for forwarding (e.g., all packets to a given prefix), mapped to the same label/LSP at the ingress LSR." },
        { id: "B20", domain: "BGP",
          text: "Which BGP extended community identifies membership of a route in specific VPNs for import/export?",
          options: ["Route target","Site-of-origin only","Local preference","Aggregator"],
          answer: 0, multi: false,
          explanation: "The route-target extended community drives VPN import/export policy. Site-of-origin (SoO) is a separate extended community used to prevent routing loops in multihomed sites." }
      ]
    },
    // ============================================================
    {
      id: "SP-C",
      name: "Mock Exam C — Routing, IPv6 & HA",
      description: "A 20-question set focused on IGPs/BGP, IPv6, tunnels, CoS and high availability.",
      questions: [
        { id: "C1", domain: "OSPF",
          text: "Which OSPFv3 characteristic differs from OSPFv2?",
          options: ["It uses areas","It runs per-link and uses IPv6 link-local addresses for neighbor communication","It uses a Router ID","It floods LSAs"],
          answer: 1, multi: false,
          explanation: "OSPFv3 operates per-link (not per-subnet) and uses IPv6 link-local addresses as the source for protocol packets/next hops, while still using a 32-bit Router ID and areas." },
        { id: "C2", domain: "ISIS",
          text: "Which IS-IS level is analogous to the OSPF backbone and interconnects areas?",
          options: ["Level 1","Level 2","Level 0","Level 3"],
          answer: 1, multi: false,
          explanation: "Level 2 is the inter-area backbone (like OSPF area 0). Level 1 is intra-area; L1/L2 routers connect the two." },
        { id: "C3", domain: "BGP",
          text: "Which statement about EBGP vs IBGP next-hop handling is correct by default?",
          options: ["EBGP changes next hop to itself when advertising; IBGP does not change it","IBGP always changes the next hop","Neither changes the next hop","Both strip the next hop"],
          answer: 0, multi: false,
          explanation: "An EBGP speaker sets the next hop to itself when advertising to an EBGP peer; when re-advertised into IBGP the next hop is unchanged, which is why 'next-hop self' or an IGP route to that next hop is needed." },
        { id: "C4", domain: "IPV6",
          text: "How many bits is an IPv6 address, and what is the typical interface identifier length in SLAAC?",
          options: ["64 bits total; 32-bit IID","128 bits total; 64-bit IID","128 bits total; 48-bit IID","256 bits total; 64-bit IID"],
          answer: 1, multi: false,
          explanation: "IPv6 addresses are 128 bits, commonly split into a 64-bit prefix and a 64-bit interface identifier (e.g., derived via EUI-64 or random) for SLAAC." },
        { id: "C5", domain: "IPV6",
          text: "Which IPv6 mechanism lets a host auto-configure a global address from a Router Advertisement without a DHCP server?",
          options: ["SLAAC (Stateless Address Autoconfiguration)","Stateful DHCPv6","NAT66","ARP"],
          answer: 0, multi: false,
          explanation: "SLAAC uses the prefix from Router Advertisements plus a locally generated interface ID to form a global address, without needing a DHCP server." },
        { id: "C6", domain: "IPV6",
          text: "Which address range is reserved for IPv6 unique local addresses (ULAs), the rough equivalent of RFC 1918 private space?",
          options: ["FE80::/10","FC00::/7","FF00::/8","2000::/3"],
          answer: 1, multi: false,
          explanation: "ULAs use FC00::/7 (in practice FD00::/8 for locally-assigned). FE80::/10 is link-local, FF00::/8 is multicast, and 2000::/3 is global unicast." },
        { id: "C7", domain: "TUNNELS",
          text: "Which Junos interface is used for an IP-IP (IP-over-IP) tunnel?",
          options: ["ip-","gr-","ae-","irb"],
          answer: 0, multi: false,
          explanation: "IP-IP tunnels use ip- interfaces; GRE tunnels use gr- interfaces. Both require tunnel services (tunnel PIC / lt/RE capability)." },
        { id: "C8", domain: "TUNNELS",
          text: "A key operational drawback of tunneling (GRE/IP-IP) that must be planned for is what?",
          options: ["It encrypts by default","Added encapsulation overhead reduces the effective MTU, risking fragmentation","It disables the IGP","It requires MPLS"],
          answer: 1, multi: false,
          explanation: "Tunnel headers add overhead, lowering the payload MTU; without MTU/MSS adjustment or PMTUD this causes fragmentation or black-holing of large packets. GRE/IP-IP are not encrypted." },
        { id: "C9", domain: "HA",
          text: "Graceful Routing Engine Switchover (GRES) by itself preserves what?",
          options: ["Full routing-protocol adjacencies","Kernel and interface/forwarding state so the backup RE can take over hardware","Nothing","BGP sessions with no other feature"],
          answer: 1, multi: false,
          explanation: "GRES synchronizes kernel/interface state to the backup RE for a fast hardware takeover, but routing-protocol adjacencies survive only with NSR or graceful restart added." },
        { id: "C10", domain: "HA",
          text: "BFD improves convergence by doing what?",
          options: ["Encrypting hellos","Detecting forwarding-path failures in sub-second time and notifying the routing protocol","Aggregating links","Assigning labels"],
          answer: 1, multi: false,
          explanation: "BFD is a lightweight hello mechanism providing sub-second failure detection between two systems, letting OSPF/IS-IS/BGP react far faster than native timers." },
        { id: "C11", domain: "HA",
          text: "VRRP provides redundancy at which layer of the network?",
          options: ["Core LSP layer","First-hop gateway (default gateway) redundancy for hosts","MPLS label layer","Physical layer only"],
          answer: 1, multi: false,
          explanation: "VRRP provides a redundant first-hop/default-gateway virtual IP for hosts; a master forwards and a backup takes over on failure." },
        { id: "C12", domain: "PIR",
          text: "What is the default Junos route preference order (lower = preferred) among these?",
          options: ["OSPF internal (10) < IS-IS L1 (15) < RSVP (7)","RSVP (7) < OSPF internal (10) < IS-IS L1 (15) < BGP (170)","BGP (170) < OSPF (10)","Static (5) is worse than BGP (170)"],
          answer: 1, multi: false,
          explanation: "Typical defaults: Direct/Local 0, RSVP 7, LDP 9, OSPF internal 10, IS-IS L1 15, IS-IS L2 18, static 5, BGP 170. Lower is preferred; note static (5) is better than most IGPs." },
        { id: "C13", domain: "COS",
          text: "On the egress PE of an L3VPN, how is CoS typically preserved from the core to the customer?",
          options: ["The EXP bits are ignored","EXP-to-DSCP (or rewrite) mapping restores/keeps the IP CoS marking after the label is removed","CoS is impossible over MPLS","Only 802.1p is used"],
          answer: 1, multi: false,
          explanation: "CoS is carried in the label EXP field across the core; at the egress PE, classifiers/rewrite rules map EXP back to IP DSCP (or keep the original) so end-to-end CoS is maintained." },
        { id: "C14", domain: "COS",
          text: "Which CoS component controls the maximum rate at which a queue or interface transmits, smoothing bursts?",
          options: ["Classifier","Shaper (shaping-rate)","Rewrite rule","Drop profile"],
          answer: 1, multi: false,
          explanation: "A shaper (shaping-rate) caps and smooths the transmit rate, buffering bursts. Classifiers assign forwarding classes; rewrite rules re-mark; drop profiles manage congestion drops." },
        { id: "C15", domain: "BGP",
          text: "Which BGP feature helps dampen the effect of a repeatedly flapping route?",
          options: ["Route reflection","Route flap damping","Confederations","Multipath"],
          answer: 1, multi: false,
          explanation: "Route flap damping suppresses routes that flap frequently by accumulating a penalty, reducing churn; it must be used carefully to avoid over-penalizing legitimate changes." },
        { id: "C16", domain: "OSPF",
          text: "Which OSPF network type elects a DR/BDR?",
          options: ["Point-to-point","Broadcast (and NBMA)","Virtual link","Loopback"],
          answer: 1, multi: false,
          explanation: "DR/BDR election occurs on broadcast and NBMA network types to reduce adjacency count; point-to-point links form a single adjacency without a DR." },
        { id: "C17", domain: "ISIS",
          text: "By default, what is the IS-IS interface metric in Junos, and why is tuning common in SP cores?",
          options: ["Auto from bandwidth; no tuning needed","10 for all interfaces; tuning is needed for traffic engineering/path control","0; must always be set","100; matches OSPF"],
          answer: 1, multi: false,
          explanation: "Junos sets a default IS-IS metric of 10 regardless of speed, so operators tune metrics (and use wide metrics) to steer traffic in the core." },
        { id: "C18", domain: "IPV6",
          text: "Which transition technique advertises IPv6 reachability across an IPv4 MPLS core using BGP labeled IPv6 on PEs (6PE)?",
          options: ["6PE","NAT64","Teredo","Dual stack only"],
          answer: 0, multi: false,
          explanation: "6PE carries IPv6 routes with MPLS labels over an IPv4/MPLS core using MP-BGP, letting existing IPv4 LSPs transport IPv6 without upgrading the core to native IPv6." },
        { id: "C19", domain: "L2",
          text: "On MX, which family enables flexible VLAN tagging and multiple units per physical interface for L2 services?",
          options: ["family inet only","family ethernet-switching / flexible-vlan-tagging","family mpls only","family iso"],
          answer: 1, multi: false,
          explanation: "flexible-vlan-tagging (with encapsulation like flexible-ethernet-services) lets a single MX port carry multiple tagged units for different L2/L3 services and bridge domains." },
        { id: "C20", domain: "STP",
          text: "Which protection disables an edge port that unexpectedly receives a BPDU in an SP access ring/aggregation design?",
          options: ["Root guard","BPDU protect (bpdu-block)","Loop protect","MAC limiting"],
          answer: 1, multi: false,
          explanation: "BPDU protect error-disables an edge/access port that receives a BPDU, protecting the L2 topology from rogue switches or accidental loops at the edge." }
      ]
    }
  ]
};
if (typeof module !== "undefined") { module.exports = { SP_CERT }; }
